### PR TITLE
[WIP] Snapshots

### LINKED ISSUE #70: Build in support for snapshots
# Glossary 

**Snapshot**: The process of creating an image
**Image**: The artifact created from taking a snapshot

 - We need to implement and flesh out the `kubicorn snapshot` command.
 - We need to delete the `kubicorn image` command

### What is a snapshot?

A tarball. 

A tarball that holds all relevant data to rebuild a Kubernetes cluster (both infra and app).

### How do we make one?

We dump all the yaml into a directory and compress that shit up. 

No seriously, that is what we do.
We need to pull the kubicorn cluster api into the directory, as well as **all** the yaml from `kubectl`

### How do we apply one?

We do the reverse of the above. 

### Things you will need to do

1. vendor `kubectl`
2. write something that dumps all the yaml to disk
3. write something that will compress/decompress the directory into a tarball
4. verify you can create a cluster, then create some apps, then create and image
5. nuke your cluster
6. apply your newly created image
7. verify it's the same
8. win

### PR DESCRIPTION
**Pull request by kris-nova**
Closes #70

### CODE REVIEW

**Comment by kris-nova** [comment]
Fixes bugs in DigitalOcean on CentOS
Closes #70 
Vendors `client-go` and other kubernetes libs with `dep`
Fixes broken integration tests
Fixes broken AWS deployment

Sorry for the monolithic PR everyone - but I just needed to get a lot of this shit done and tidied up as we are approaching `0.1.00`

**Comment by kris-nova** [comment]
Also bumping DO droplet sizes - we are LA 12 omfg

**Comment by kris-nova** [comment]
Also introducing a new paradigm into create

you can either

1. create from snapshot
2. create from profile

and then as long as they both result in a valid state store, the program works as normal... omfg we can clone clusters

**Comment by prateekgogia** [comment]
That's big diff to review, good problem to have :) from next PR onwards can you please separate deps and actual code in different commits, so that its easier to review. Thanks.

**Comment by kris-nova** [comment]
@prateekgogia I am just working in this branch for now while it's still a WIP - if we need to pull the deps out after I remove WIP I can 😄. For now it's nice because I switch computers a lot... also see #264 where this problem goes away forever.

So is it okay if I leave it for now and when we are ready for review we can figure out what we want to do?

**Comment by prateekgogia** [comment]
@kris-nova Does this PR depends on ARK integration, or is it independent ?

**Comment by ncdc** [comment]
@kris-nova if you do want to use the Ark packages to do snapshots, let us know and we'll be happy to advise if needed

**Comment by prateekgogia** [comment]
@ncdc We added an integration draft document, I am waiting for the maintainers meeting this Friday to discuss and start the work on this. Can you please take a look #330, if you have any feedback / comments.

**Comment by kris-nova** [comment]
Closing because ARK does all this :)

**Pull request closed without merging**
