### PR TITLE
Kubernetes on DigitalOcean

### PR DESCRIPTION
**Pull request by kris-nova**
- Control Plane
- VPN mesh for node infrastructure
- Private networking
- Ubuntu

### CODE REVIEW

**Comment by kris-nova** [comment]
@jcruz2us I wanted to make sure you knew about this

**Comment by kris-nova** [comment]
Still sorting out the VPN mesh for the nodes - but I have the control plane up and running! Just need some downtime, and will be wrapping this up shortly!

**Comment by kris-nova** [comment]
Update: Sorry I have been swamped at work and still trying to write a book at the same time on all this stuff! I promise we will have k8s on digital ocean + VPN private network ASAP.. it's coming.. it's coming!

**Comment by jcruz2us** [comment]
This is very promising! I've been fiddling with this for the past day or so and here are my findings. By running

```
kubicorn create --name myfirstk8s --profile do
kubicorn apply --name myfirstk8s
```

I get the following on digitalocean...
- an operational master node
- a worker node that boots up but never joins the cluster

The logs for `kubelet.service` on the worker node showed

```
Jul 20 22:21:17 myfirstk8s-node kubelet[3479]: error: failed to run Kubelet: invalid kubeconfig: stat /etc/kubernetes/kubelet.conf: no such file or directory
Jul 20 22:21:17 myfirstk8s-node systemd[1]: kubelet.service: Main process exited, code=exited, status=1/FAILURE
Jul 20 22:21:17 myfirstk8s-node systemd[1]: kubelet.service: Unit entered failed state.
Jul 20 22:21:17 myfirstk8s-node systemd[1]: kubelet.service: Failed with result 'exit-code'.
Jul 20 22:21:22 myfirstk8s-node systemd[1]: Stopped kubelet: The Kubernetes Node Agent.
```

I verfied `/etc/kubernetes/kubelet.conf` and ran `systemctl start kubelet.service` on the worker node. The node joined the cluster and I was able to verify it with `kubectl get nodes`.

With the worker node as part of the cluster, I launched  a simple nginx container and exposed  it to the internet via a node port!!

A little hiccup but this is looking great! Thank you and let me know if I can be of any help.

**Comment by kris-nova** [comment]
The last push I made should fix all the kubelet concerns 

Now I am just working on setting up a VPN mesh so that private networking is actually "private"

**Comment by kris-nova** [comment]
should have this in by the end of the night sans tests - meaning it will be ready to run (and therefor break) tomorrow

**Comment by kris-nova** [comment]
Alright folks.. here goes nothing

**Pull request merged**
