### PR TITLE
Updated cloud/README.md to describe how to add new cloud provider

### PR DESCRIPTION
**Pull request by deitch**
This is a first attempt. Adding a new cloud provider requires touching a number of different places. Would appreciate corrections.

### CODE REVIEW

**Comment by vielmetti** [comment]
This improves on #480

**Comment by xmudrii** [comment]
@deitch Thank you so much for your contribution to the kubicorn project! We really appreciate it.
This looks good to me. However, I would move this to [project's documentation](https://github.com/kris-nova/kubicorn/tree/master/docs/_documentation) and then link it to all relevant READMEs. As you said, it requires touching a many different places, so I think having it in documentation would make more sense.

**Comment by deitch** [comment]
Sure @xmudrii . Happy to move it over there and just link to it from this README.

**Comment by deitch** [comment]
I moved it over, but that does make all of the links wrong, since they were relative to `./cloud/`. Where is this stuff published? Should I just link to the absolute path of the GitHub repo?

**Comment by xmudrii** [comment]
@deitch Thanks for the fast response. Yes, linking it to the absolute path of repo is good enough.

**Comment by deitch** [comment]
Done.

**Comment by xmudrii** [comment]
@deitch Once again, thank you very much! It looks good to me. I'll go ahead and merge it.

**Comment by deitch** [comment]
Now we will find out how well they work as I implement Packet! :-)

**Pull request merged**
