### PR TITLE
Added pre-release badge to kubicon.io

### LINKED ISSUE #379: Add pre-release badge to kubicorn.io
Can we please have some sort of noticable warning on the page that let's users know we are pre-release but working hard to get to `1.0.0`

We could add it to the [main page](http://kubicorn.io). [Here is the HTML file for the home page](https://github.com/kris-nova/kubicorn/blob/master/docs/_layouts/home.html).

If you'd like to learn more about `kubicorn` project, you can read [The Project Walkthrough](http://kubicorn.io/documentation/project-walkthrough.html).
If you have any question, comment on the issue, join us on the `#kubicorn` channel in the [Gophers Slack community](https://invite.slack.golangbridge.org/) or open a PR. We'll always do everything we can to get the PR though.

### PR DESCRIPTION
**Pull request by Ch3ck**
Fixes #379

### CODE REVIEW

**Comment by xmudrii** [comment]
I will leave this on @ellenkorbes for review :)

**Comment by kris-nova** [comment]
Yep also wanting to hear back from @ellenkorbes - this is out of my league and is her department :)

**Comment by Ch3ck** [comment]
I see in the mean time I'll work on another issue @xmudrii @kris-nova

**Comment by ellenkorbes** [comment]
Hi everyone, sorry for the delay.

I'm not sure the addition fits the aesthetic of the website TBH. Screenshot:

screenshot_20171010_115212

It doesn't fill the width of the website, and it looks to me like it's just floating there. Perhaps it'd work to stick that text at the bottom of the section above, but then the gear icon would look out of place. Maybe we could stick to just the "Warning" and the text, with no icon? IDK. Thoughts?

**Comment by xmudrii** [comment]
@ellenkorbes I think it should stay at the same place as it is right now. I would just do the following:
1) Align it with the 'Core Values' text.
2) Put it in some box like the Core Values, but with some yellowish color. 
3) Recolor the gear icon to some yellow or red as well.

Maybe we could work something for 'Warning' title text but let's leave it as it is.

WDYT?

**Comment by Ch3ck** [comment]
Thanks for the feedback @xmudrii @ellenkorbes I'll make the changes and see.

**Comment by Ch3ck** [comment]
@xmudrii @ellenkorbes Issues fixed, this should be ready to merge now

**Pull request merged**
