### PR TITLE
Build kubicorn from source (issue #77)

### PR DESCRIPTION
**Pull request by arashkaffamanesh**
Please add additional instruction to build kubicorn from source #77

### CODE REVIEW

**Comment by kris-nova** [comment]
@arashkaffamanesh can you please resolve the merge conflict?

**Comment by arashkaffamanesh** [comment]
I couldn't resolve the merge conflict and closed the PR accidentally, I'll reopen it and try again.

**Comment by kris-nova** [comment]
You should be able to click resolve conflicts and do it directly in Github

**Comment by arashkaffamanesh** [comment]
The resolve conflicts button is greyed out with the hint that "these conflicts are too complex to resolve in the web editor" :-(

**Comment by kris-nova** [comment]
Hrmm you can resolve from the command line? Or maybe just start a new PR based on a fresh copy of master?

**Comment by kris-nova** [comment]
@arashkaffamanesh any update on this?

**Comment by shwsun** [comment]
@arashkaffamanesh One way to resolve merging conflict is to get a up-to-date version of kubicorn and rebase your changes on top of it.

**Comment by kris-nova** [comment]
Closing this PR as it's stale. Please re open if necessary! 😃

**Pull request closed without merging**
