### PR TITLE
Update deps, remove glide, use dep.

### PR DESCRIPTION
**Pull request by darron**
Lots of changes but it still builds a binary.

### CODE REVIEW

**Comment by darron** [comment]
This should fix #15

**Comment by darron** [comment]
This is what I did - you don't have to:

```
glide update
dep init
dep ensure
```

**Comment by kris-nova** [comment]
Are we still blocked on this?

**Comment by geojaz** [comment]
Can you double check to make sure it works for you? If you can make it work correctly, I'll continue to look at it/bring Sam in.

**Comment by kris-nova** [comment]
let me run it

**Comment by kris-nova** [comment]
@geojaz check out `dep ensure -update`, also when did you last build `dep`?

This branch builds fine and compiles for me.. merging :)

**Pull request merged**
