### PR TITLE
Remove --name flag from google walkthough doc

### PR DESCRIPTION
**Pull request by ajitak**

### CODE REVIEW

**Comment by xmudrii** [comment]
@ajitak @pipejakob there's some conflicts blocking the merge. Can you please take a look, so I can merge it?

**Comment by xmudrii** [comment]
@ajitak @pipejakob Also, AFAIK, there's no need to update `docs_old`. It's serving here for "history" purposes, the latest documentation is [here](https://github.com/kris-nova/kubicorn/blob/master/docs/_documentation/google-walkthrough.md). Can you please update that file as well (if needed)?

**Comment by ajitak** [comment]
@xmudrii Thanks, I have resolved conflict and updated the latest doc.

**Comment by xmudrii** [comment]
@ajitak Thank you very much, LGTM. :shipit:

**Pull request merged**
