### PR TITLE
Rebase to change incorrect author info

### PR DESCRIPTION
**Pull request by k4k**
I accidentally had the wrong author info set in git when I made my commits. This fixes all of those commits to have the correct author information.

### CODE REVIEW

**Comment by k4k** [comment]
I'm not sure why it shows me on all of these commits. When I view `git log` after the rebase locally it only shows me as the author on the following commits:

* `9cef1331ea08b3701405fb98f1f614502a1f7656`
* `9a4a513e9b5e21436147cb829f3990cc18f1c206`
* `626be591c3fe3da99557a8d204a4ba709ed38ee1`
* `b770da15dbc427c322dcc30eae0f509b38369d53`
* `960ff069d730bba67164a2474b15bdfd0c72b5a4`
* `a46061998817f5cb70651e65ae1a2ce1b4b7d3a9`

**Comment by kris-nova** [comment]
I think we need to do some `git filter-branch` magic to get rid of these unfortunately.. git has a concept of 2 email addresses (author and committer I **think**)

**Comment by kris-nova** [comment]
I know you can `git rebase -i` and edit all of your commits to be with **both** your old/new email addresses.. re-writing entire history however is a bit trickier.. last time I did it was in https://github.com/golang/dep/pull/453 and it was not very fun :disappointed:

**Comment by k4k** [comment]
So, what I ended up doing here was an interactive rebase against the commit
before my first one I did. I went through and marked each commit of mine
from the on for editing and amended the author on each of those commits. I
was unable to find a way cherry pick rebas only my commits, I had to start
from the commit before my first one and rebase all of them. I'll play with
it some more today and see if I can figure something out to keep myself off
the other commits. Like I said on Slack, this isn't a huge deal but I
prefer to use my personal address on open source projects for continuity.

**Comment by k4k** [comment]
Closing in favor of #101

**Pull request closed without merging**
