### PR TITLE
Use SSH Agent if present

### PR DESCRIPTION
**Pull request by paulczar**
If ssh agent is running and SSH_AUTH_SOCK is set we
should attempt to use it rather than try to load the keys
this way we can bypass need to ask for passphrase.

This might address #91

### CODE REVIEW

**Comment by k4k** [comment]
This is great! Definitely something we wanted to support. I'm not sure that Travis will have SSH agent running so I'm not sure if it solves #.91 but someone with more Travis experience may know better.

**Comment by k4k** [comment]
I'm having trouble making this work. I have my ssh keys added to ssh-agent but I'm still being prompted for a password. @paulczar what platforms did you test this on? I'm wondering if there's something strange with my environment causing `sshAgent()` to fail.

**Comment by kris-nova** [comment]
Out of town at the moment - will check out ASAP thank you so much for the PR

**Comment by kris-nova** [comment]
The code looks sound, merging to master and we can iterate if needed. @k4k can we open an issue to track your agent not working and track there?

**Comment by kris-nova** [comment]
See issue #104 regarding standardizing an scp package

**Pull request merged**
