### PR TITLE
Lint code and fix imports order using gofmt task

### PR DESCRIPTION
**Pull request by aledbf**
replaces #205

### CODE REVIEW

**Comment by kris-nova** [comment]
Do we have something in `.travs.yml` to check for this?

**Comment by aledbf** [comment]
@kris-nova no but that should be easy to add. Just abort ci when code with errors is being pushed?

**Comment by kris-nova** [comment]
yep - just have CI yell at us if something fails whatever check you are running here

**Comment by aledbf** [comment]
@kris-nova can I do that in a different PR? This PR is just the result of running `make gofmt` (it changes the files).
I a different PR I'll add a different task to check the code and abort in case of errors

**Comment by kris-nova** [comment]
Sounds good - merging

**Pull request merged**
