### PR TITLE
Friends

### LINKED ISSUE #363: Friends of kubicorn
## Ark

Thanks to the fantastic works from our friends at Heptio, we can easily help you snapshot and recreate your entire `kubernetes` platform using Heptio's [Ark](https://github.com/heptio/ark)

heptio-ark 1024px

## Calico

We use [Project Calico](https://www.projectcalico.org) to make **CNI** problems go away! Thanks to our friends at Tigera, we now can help you get kubernetes up and running in no time using a rock solid CNI provider.

image

## Weave

We use [Weavenet](https://www.weave.works/oss/net) to help control our clusters! Thanks to our friends at Weave we now offer a great experience for networking in different clouds, and a seamless user experience. 

image

### PR DESCRIPTION
**Pull request by ellenkorbes**
Closes #363

### CODE REVIEW

**Comment by prateekgogia** [comment]
@ellenkorbes Is there a way to keep Kubicorn related documentation separate and kubicorn.io files (like _include, _layout folders) separate may be in a sub-directory ? What I want to keep is docs directory cleaner, so that if someone is visiting the project for the first time, it doesn't get confusing which files to look.

**Comment by xmudrii** [comment]
@prateekgogia As far as I understood, I think we want to make user use `kubicorn.io` instead of docs on GitHub. That could make things easier and better for user. We also need to work on #339, which will show user where she/he should read the docs.

**Comment by ellenkorbes** [comment]
@prateekgogia I don't think so. GitHub Pages isn't very flexible, the website files can either be at `/` or at `/docs`. What we can do is have `/docs/README.md` do a better job at explaining how things work.

And as @xmudrii said, I was under the impression we wanted to website to be the main place to read documentation, not the repo.

**Comment by ellenkorbes** [comment]
There's also the option of having a separate repo for the website, à la https://github.com/gohugoio/hugoDocs

**Comment by xmudrii** [comment]
@ellenkorbes this could be an good idea, but I wouldn't do it at this point. We still didn't reached some stability point, API is changed with every other PR: new variables are added, etc.
At this point, it would just add an additional step for contributors as they'll have to update two repos.

Once we reach some point when changes are less breaking, this could be an awesome idea.

**Comment by ellenkorbes** [comment]
Sounds good to me.

**Pull request merged**
